package vrbaidu.top.city.model;

import java.io.Serializable;

public class CityMsg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table varbaidu_code_msg
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.id
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.pid
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.shortname
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.name
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.merger_name
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String mergerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.level
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.pinyin
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.code
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.zip_code
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.first
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String first;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.lng
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column varbaidu_code_msg.lat
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    private String lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.id
     *
     * @return the value of varbaidu_code_msg.id
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.id
     *
     * @param id the value for varbaidu_code_msg.id
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.pid
     *
     * @return the value of varbaidu_code_msg.pid
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.pid
     *
     * @param pid the value for varbaidu_code_msg.pid
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.shortname
     *
     * @return the value of varbaidu_code_msg.shortname
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.shortname
     *
     * @param shortname the value for varbaidu_code_msg.shortname
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.name
     *
     * @return the value of varbaidu_code_msg.name
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.name
     *
     * @param name the value for varbaidu_code_msg.name
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.merger_name
     *
     * @return the value of varbaidu_code_msg.merger_name
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.merger_name
     *
     * @param mergerName the value for varbaidu_code_msg.merger_name
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.level
     *
     * @return the value of varbaidu_code_msg.level
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.level
     *
     * @param level the value for varbaidu_code_msg.level
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.pinyin
     *
     * @return the value of varbaidu_code_msg.pinyin
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.pinyin
     *
     * @param pinyin the value for varbaidu_code_msg.pinyin
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.code
     *
     * @return the value of varbaidu_code_msg.code
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.code
     *
     * @param code the value for varbaidu_code_msg.code
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.zip_code
     *
     * @return the value of varbaidu_code_msg.zip_code
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.zip_code
     *
     * @param zipCode the value for varbaidu_code_msg.zip_code
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.first
     *
     * @return the value of varbaidu_code_msg.first
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getFirst() {
        return first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.first
     *
     * @param first the value for varbaidu_code_msg.first
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setFirst(String first) {
        this.first = first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.lng
     *
     * @return the value of varbaidu_code_msg.lng
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.lng
     *
     * @param lng the value for varbaidu_code_msg.lng
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setLng(String lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column varbaidu_code_msg.lat
     *
     * @return the value of varbaidu_code_msg.lat
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column varbaidu_code_msg.lat
     *
     * @param lat the value for varbaidu_code_msg.lat
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    public void setLat(String lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table varbaidu_code_msg
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", shortname=").append(shortname);
        sb.append(", name=").append(name);
        sb.append(", mergerName=").append(mergerName);
        sb.append(", level=").append(level);
        sb.append(", pinyin=").append(pinyin);
        sb.append(", code=").append(code);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", first=").append(first);
        sb.append(", lng=").append(lng);
        sb.append(", lat=").append(lat);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table varbaidu_code_msg
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CityMsg other = (CityMsg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getShortname() == null ? other.getShortname() == null : this.getShortname().equals(other.getShortname()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMergerName() == null ? other.getMergerName() == null : this.getMergerName().equals(other.getMergerName()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getPinyin() == null ? other.getPinyin() == null : this.getPinyin().equals(other.getPinyin()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getZipCode() == null ? other.getZipCode() == null : this.getZipCode().equals(other.getZipCode()))
            && (this.getFirst() == null ? other.getFirst() == null : this.getFirst().equals(other.getFirst()))
            && (this.getLng() == null ? other.getLng() == null : this.getLng().equals(other.getLng()))
            && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table varbaidu_code_msg
     *
     * @mbggenerated Sat Apr 08 15:08:34 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getShortname() == null) ? 0 : getShortname().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMergerName() == null) ? 0 : getMergerName().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getPinyin() == null) ? 0 : getPinyin().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getZipCode() == null) ? 0 : getZipCode().hashCode());
        result = prime * result + ((getFirst() == null) ? 0 : getFirst().hashCode());
        result = prime * result + ((getLng() == null) ? 0 : getLng().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        return result;
    }
}