package vrbaidu.top.login.dao;

import com.istock.base.mybatis.BaseMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import vrbaidu.top.login.model.RolePermission;
import vrbaidu.top.login.model.RolePermissionExample;

public interface RolePermissionMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbggenerated Sat Mar 11 22:44:23 CST 2017
     */
    int countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbggenerated Sat Mar 11 22:44:23 CST 2017
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbggenerated Sat Mar 11 22:44:23 CST 2017
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbggenerated Sat Mar 11 22:44:23 CST 2017
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbggenerated Sat Mar 11 22:44:23 CST 2017
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbggenerated Sat Mar 11 22:44:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbggenerated Sat Mar 11 22:44:23 CST 2017
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);
}