package vrbaidu.top.login.dao;

import com.istock.base.mybatis.BaseMapper;
import org.apache.ibatis.annotations.Param;
import vrbaidu.top.login.model.UserPermission;
import vrbaidu.top.login.model.UserPermissionExample;

import java.util.List;

public interface UserPermissionMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int countByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int deleteByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int insert(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int insertSelective(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    List<UserPermission> selectByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    UserPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserPermission record, @Param("example") UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int updateByExample(@Param("record") UserPermission record, @Param("example") UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int updateByPrimaryKeySelective(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    int updateByPrimaryKey(UserPermission record);
}