package vrbaidu.top.login.model;

import java.io.Serializable;

public class UserPermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.id
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.url
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.name
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.id
     *
     * @return the value of u_permission.id
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.id
     *
     * @param id the value for u_permission.id
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.url
     *
     * @return the value of u_permission.url
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.url
     *
     * @param url the value for u_permission.url
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.name
     *
     * @return the value of u_permission.name
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.name
     *
     * @param name the value for u_permission.name
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", url=").append(url);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserPermission other = (UserPermission) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated Sat Mar 11 22:34:26 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }
}